#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/"
export LD_LIBRARY_PATH="$GAMEDIR/tools/libs.aarch64:$LD_LIBRARY_PATH"
export TOOLDIR="$GAMEDIR/tools"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/innoextract"

cd "$GAMEDIR"

EXE=$(find "$DATADIR" -maxdepth 1 -name "setup*.exe")
"$TOOLDIR/innoextract" -e -d "$GAMEDIR" $EXE
mv "$GAMEDIR"/app/* "$GAMEDIR/"

# Tidy up a bit
rm -rf "$GAMEDIR/tmp" "$GAMEDIR/app"
rm "$GAMEDIR"/*.dll "$GAMEDIR"/*.exe "$GAMEDIR"/*.bin
