#/bin/bash

HOSTROOT=`pwd`
DOCKERROOT=/root

PORTDIR=$1
PORTNAME=`basename $PORTDIR`
SRCDIR=$PORTDIR/src
SETUPSCRIPT=$SRCDIR/docker-setup.txt
PRODUCTSCRIPT=$SRCDIR/retrieve-products.txt
BUILDSCRIPT=$SRCDIR/build.txt

BUILDDIR=build-port

mkdir $HOSTROOT/$BUILDDIR
cd $HOSTROOT/$BUILDDIR
cp $HOSTROOT/$SRCDIR/* .
$HOSTROOT/$SETUPSCRIPT $PORTNAME-build

sleep 5

docker exec $PORTNAME-build /bin/bash -c "cd $BUILDDIR && $DOCKERROOT/$BUILDSCRIPT"

$HOSTROOT/$PRODUCTSCRIPT $HOSTROOT/$BUILDDIR $HOSTROOT/$PORTDIR
