name: Build Perfect Dark
on:
  # Build on request
  workflow_dispatch
#  schedule:
#    - cron:  '5 4 * * *'

jobs:
  build:
    uses: ./.github/workflows/build_port.yaml
    with:
      port-name: "Perfect Dark"
      short-name: PerfectDark
      port-dir: perfectdark
      build-type: release
      email: ben@willmore.eu
