name: Build Seven Kingdoms
on:
  # Build on request
  workflow_dispatch
#  schedule:
#    - cron:  '5 4 * * *'

jobs:
  build:
    uses: ./.github/workflows/build_port.yaml
    with:
      port-name: "Seven Kingdoms"
      short-name: SevenKingdoms
      port-dir: sevenkingdoms
      build-type: release
      email: ben@willmore.eu
