name: Build La-Mulana
on:
  # Build on request
  workflow_dispatch
#  schedule:
#    - cron:  '5 4 * * *'

jobs:
  build:
    uses: ./.github/workflows/build_port.yaml
    with:
      port-name: "La-Mulana"
      short-name: La-Mulana
      port-dir: la-mulana
      build-type: release
      email: ben@willmore.eu
